version: '2'
services:
  ccrimongo:
    container_name: ccrimongo
    image: mongo:3.6.3
    ports:
    - 27107:27107

  ccridocument:
    container_name: ccridocument
    image: thorlogic/ccri-document:latest
    depends_on:
    - ccrimongo
    links:
    - ccrimongo
    environment:
    - fhir.resource.serverBase=http://167.99.202.134
    - fhir.resource.serverName=Appointment Booking RI FHIR Server
    - fhir.resource.serverVersion=3.5.1-SNAPSHOT
    - spring.data.mongodb.uri=mongodb://ccrimongo:27017/careconnect-nosql
    - spring.data.mongodb.database=careconnect-nosql
    ports:
    - 8181:8181


